### ISSUE TITLE
How to write tests for the local module?

### ISSUE THREAD

**Issue by BrianSo** [ktsn/vuex-local#4]
For vuex, I can write tests by easily import my module directly.
How can I achieve the same thing in vuex-local?

Should I write this? (using the example in readme)

```html
<script>
// Counter.vue
let uid = 0

export const module = {
  state: {
    count: 10
  },
  getters: {
    half: state => state.count / 2
  },
  actions: {
    asyncIncrement ({ commit }) {
      setTimeout(() => {
        commit('increment') // this commit can only affect local mutation
      }, 1000)
    }
  },
  mutations: {
    increment (state) {
      state.count += 1
    }
  }
}

export default {
  local () {
    uid += 1

    return Object.assign({
      name: 'counter' + uid,
    },module);
  }
}
</script>

<script>
// test.js
import {module} from './Counter'

// test module...

</script>
```

It seems there is no documentation about this. So I think adding to the Readme would be a big help.

In addition, adding `npm install vuex-local` to the readme will also help.

**Comment by ktsn** [comment]
I think we can just call local option and get the local module.
After getting the local module, we can test it as same way as ordinary Vuex module.

> It seems there is no documentation about this. So I think adding to the Readme would be a big help.
> In addition, adding npm install vuex-local to the readme will also help.

PR welcome :)

**Comment by BrianSo** [comment]
Thank you! It seems reasonable. I will try it later as I am still rushing in my project. Hopefully I could give some feedback in winter.
